name: dna-is-synthesizable
description: A github action to check if a part is synthesizable from a given Genbank file.
inputs:
    input-dir:  # id of input
        description: 'Directory where all the input genbank files will be read'
        required: true
        default: 'input'
    input-pattern:
        description: 'Regex to filter files in the input directory'
        required: true
        default: '.*\.\(gb\|gbk\)'
    output-dir:
        description: 'Directory where all the output genbank files will be written'
        required: true
        default: 'output'
    input-username:
        description: 'IDT account username'
        required: true
    input-password:
        description: 'IDT account password'
        required: true
    input-client-id:
        description: 'IDT API ClientId'
        required: true
    input-client-secret:
        description: 'IDT API ClientSecret'
        required: true
    output-alert:
        description: 'Display an error when a non-synthesizable sequence is found'
        required: false
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.input-dir           }}
        - ${{ inputs.output-dir          }}
        - ${{ inputs.input-pattern       }}
        - ${{ inputs.input-username      }}
        - ${{ inputs.input-password      }}
        - ${{ inputs.input-client-id     }}
        - ${{ inputs.input-client-secret }}
        - ${{ inputs.output-alert        }}
author: Friendzymes Team
branding:
    icon:  'layers'
    color: 'purple'
